version: '3'

services:
  db:
    restart: always
    image: postgres

    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  web:
    build: .
    tty: true
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    ports:
      - '8080:8080'
    volumes:
      - .:/code
    depends_on:
      - db
      - minio

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data: